plugins {
    id("java")
    id("io.qameta.allure") version '4.1.0'
}

repositories {
    mavenCentral()
}

allure {
    report {
        version.set("2.45.0")
    }
    adapter { // отвечает за появление папочки build/allure-results
        aspectjWeaver.set(true) //обработка аннотации @Step
        frameworks {
            junit5 { //название фреймворка
                adapterVersion.set("2.35.4") //версия интеграции фреймворка и Allure
            }
        }
    }
}

dependencies {
    testImplementation(
            "com.codeborne:selenide:7.16.1",
            'org.junit.jupiter:junit-jupiter:6.1.0',
            'io.qameta.allure:allure-selenide:2.35.4'
    )
    testRuntimeOnly(
            "org.junit.platform:junit-platform-launcher"
    )
}


tasks.withType(Test) {
    useJUnitPlatform()
    systemProperties(System.getProperties())

    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}
